
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.HButtonBox hbuttonbox2;
	private global::Gtk.Entry QueryText;
	private global::Gtk.Entry QueryOutputText;
	private global::Gtk.DrawingArea drawingarea1;
	private global::Gtk.DrawingArea da;
	private global::Gtk.Button button1;
	private global::Gtk.Button RollKp;
	private global::Gtk.Label RollCurrKp;
	private global::Gtk.Button PitchKi;
	private global::Gtk.Label PitchCurrKi;
	private global::Gtk.Button ManualMode;
	private global::Gtk.Button DirectedMode;
	private global::Gtk.Button AutoMode;
	private global::Gtk.Button ThrottleCalibMode;
	private global::Gtk.Button RollCalibMode;
	private global::Gtk.Button PitchCalibMode;
	private global::Gtk.Button YawCalibMode;
	private global::Gtk.Label ModesLabel;
	private global::Gtk.Label CurMode;
	private global::Gtk.Button RollKi;
	private global::Gtk.Label RollCurrKi;
	private global::Gtk.Button PitchKp;
	private global::Gtk.Label PitchCurrKp;
	private global::Gtk.Label TasLabel;
	private global::Gtk.Label TasEntry;
	private global::Gtk.Button NewTas;
	private global::Gtk.Label SelTas;
	private global::Gtk.Label AltLabel;
	private global::Gtk.Button NewAlt;
	private global::Gtk.Label SelAlt;
	private global::Gtk.Label RollEntry;
	private global::Gtk.Button YawKp;
	private global::Gtk.Label YawCurrKp;
	private global::Gtk.Button YawKi;
	private global::Gtk.Label YawCurrKi;
	private global::Gtk.Label PitchEntry;
	private global::Gtk.Label YawEntry;
	private global::Gtk.Label HeadLabel;
	private global::Gtk.Label YawLabel;
	private global::Gtk.Label RollLabel;
	private global::Gtk.Button ThrottleKp;
	private global::Gtk.Label ThrottleCurrKp;
	private global::Gtk.Button ThrottleKi;
	private global::Gtk.Label ThrottleCurrKi;
	private global::Gtk.Label PitchLabel;
	private global::Gtk.Label ThorttleLabel;
	private global::Gtk.Label ThrottleEntry;
	private global::Gtk.Label CurAlt;
	private global::Gtk.Button NewHeading;
	private global::Gtk.Label SelHEad;
	private global::Gtk.Label CurHead;
	private global::Gtk.Button NewRollRef;
	private global::Gtk.Button NewPitchRef;
	private global::Gtk.Button NewYawRef;
	private global::Gtk.Button NewThrottleRef;
	private global::Gtk.Label CurRollRef;
	private global::Gtk.Label CurPitchRef;
	private global::Gtk.Label CurYawRef;
	private global::Gtk.Label CurThrotRef;
	private global::Gtk.Label InCh2;
	private global::Gtk.Label InCh1;
	private global::Gtk.Label InCh3;
	private global::Gtk.Label InCh1Val;
	private global::Gtk.Label InCh2Val;
	private global::Gtk.Label InCh4Val;
	private global::Gtk.Label InCh3Val;
	private global::Gtk.Label InCh4;
	private global::Gtk.Button ThrottleMeanVal;
	private global::Gtk.Label CurThrottleMeanVal;
	private global::Gtk.Button RollMeanVal;
	private global::Gtk.Button PitchMeanVal;
	private global::Gtk.Label CurRollMeanVal;
	private global::Gtk.Button YawMeanVal;
	private global::Gtk.Label CurPitchMeanVal;
	private global::Gtk.Label CurYawMeanVal;
	private global::Gtk.Button ThrottleInitialValue;
	private global::Gtk.Button RollInitialValue;
	private global::Gtk.Button YawInitialValue;
	private global::Gtk.Button PitchInitialValue;
	private global::Gtk.Label CurThrotInitialValue;
	private global::Gtk.Label CurRollInitialVal;
	private global::Gtk.Label CurPitchInitialVal;
	private global::Gtk.Button ActThrottle;
	private global::Gtk.Button ActRoll;
	private global::Gtk.Button ActPitch;
	private global::Gtk.Button ActYaw;
	private global::Gtk.Label CurActThrottle;
	private global::Gtk.Label CuActRoll;
	private global::Gtk.Label CurActPitch;
	private global::Gtk.Label CurActYaw;
	private global::Gtk.Button GetInitialData;
	private global::Gtk.Label OutCh1Val;
	private global::Gtk.Label OutCh2Val;
	private global::Gtk.Label OutCh3Val;
	private global::Gtk.Label OutCh4Val;
	private global::Gtk.Label OutCh1;
	private global::Gtk.Label OutCh2;
	private global::Gtk.Label OutCh3;
	private global::Gtk.Label OutCh4;
	private global::Gtk.Label InCh1Width;
	private global::Gtk.Label InCh2Width;
	private global::Gtk.Label InCh3Width;
	private global::Gtk.Label InCh4Width;
	private global::Gtk.Label OutCh3Width;
	private global::Gtk.Label OutCh4Width;
	private global::Gtk.Label OutCh2Width;
	private global::Gtk.Label OutCh1Width;
	private global::Gtk.Button GetCurrYaw;
	private global::Gtk.Label CurYawInitVal;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.hbuttonbox2 = new global::Gtk.HButtonBox ();
		this.hbuttonbox2.Name = "hbuttonbox2";
		this.fixed1.Add (this.hbuttonbox2);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.hbuttonbox2]));
		w1.X = 420;
		w1.Y = 126;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.QueryText = new global::Gtk.Entry ();
		this.QueryText.CanFocus = true;
		this.QueryText.Name = "QueryText";
		this.QueryText.IsEditable = true;
		this.QueryText.InvisibleChar = '•';
		this.fixed1.Add (this.QueryText);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.QueryText]));
		w2.X = 8;
		w2.Y = 10;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.QueryOutputText = new global::Gtk.Entry ();
		this.QueryOutputText.CanFocus = true;
		this.QueryOutputText.Name = "QueryOutputText";
		this.QueryOutputText.IsEditable = true;
		this.QueryOutputText.InvisibleChar = '•';
		this.fixed1.Add (this.QueryOutputText);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.QueryOutputText]));
		w3.X = 8;
		w3.Y = 42;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.drawingarea1 = new global::Gtk.DrawingArea ();
		this.drawingarea1.Name = "drawingarea1";
		this.fixed1.Add (this.drawingarea1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.drawingarea1]));
		w4.X = 473;
		w4.Y = 134;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.da = new global::Gtk.DrawingArea ();
		this.da.Name = "da";
		this.fixed1.Add (this.da);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.da]));
		w5.X = 346;
		w5.Y = 194;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("AcceptQuery");
		this.fixed1.Add (this.button1);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button1]));
		w6.X = 171;
		w6.Y = 9;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.RollKp = new global::Gtk.Button ();
		this.RollKp.CanFocus = true;
		this.RollKp.Name = "RollKp";
		this.RollKp.UseUnderline = true;
		this.RollKp.Label = global::Mono.Unix.Catalog.GetString ("Roll Kp");
		this.fixed1.Add (this.RollKp);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.RollKp]));
		w7.X = 273;
		w7.Y = 9;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.RollCurrKp = new global::Gtk.Label ();
		this.RollCurrKp.Name = "RollCurrKp";
		this.RollCurrKp.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.RollCurrKp);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.RollCurrKp]));
		w8.X = 336;
		w8.Y = 13;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.PitchKi = new global::Gtk.Button ();
		this.PitchKi.CanFocus = true;
		this.PitchKi.Name = "PitchKi";
		this.PitchKi.UseUnderline = true;
		this.PitchKi.Label = global::Mono.Unix.Catalog.GetString ("Pitch Ki");
		this.fixed1.Add (this.PitchKi);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.PitchKi]));
		w9.X = 383;
		w9.Y = 42;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.PitchCurrKi = new global::Gtk.Label ();
		this.PitchCurrKi.Name = "PitchCurrKi";
		this.PitchCurrKi.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.PitchCurrKi);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.PitchCurrKi]));
		w10.X = 455;
		w10.Y = 46;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ManualMode = new global::Gtk.Button ();
		this.ManualMode.CanFocus = true;
		this.ManualMode.Name = "ManualMode";
		this.ManualMode.UseUnderline = true;
		this.ManualMode.Label = global::Mono.Unix.Catalog.GetString ("Manual");
		this.fixed1.Add (this.ManualMode);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ManualMode]));
		w11.X = 11;
		w11.Y = 72;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.DirectedMode = new global::Gtk.Button ();
		this.DirectedMode.CanFocus = true;
		this.DirectedMode.Name = "DirectedMode";
		this.DirectedMode.UseUnderline = true;
		this.DirectedMode.Label = global::Mono.Unix.Catalog.GetString ("Directed");
		this.fixed1.Add (this.DirectedMode);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.DirectedMode]));
		w12.X = 78;
		w12.Y = 73;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.AutoMode = new global::Gtk.Button ();
		this.AutoMode.CanFocus = true;
		this.AutoMode.Name = "AutoMode";
		this.AutoMode.UseUnderline = true;
		this.AutoMode.Label = global::Mono.Unix.Catalog.GetString ("Auto");
		this.fixed1.Add (this.AutoMode);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.AutoMode]));
		w13.X = 157;
		w13.Y = 73;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ThrottleCalibMode = new global::Gtk.Button ();
		this.ThrottleCalibMode.CanFocus = true;
		this.ThrottleCalibMode.Name = "ThrottleCalibMode";
		this.ThrottleCalibMode.UseUnderline = true;
		this.ThrottleCalibMode.Label = global::Mono.Unix.Catalog.GetString ("Cal. Throttle");
		this.fixed1.Add (this.ThrottleCalibMode);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ThrottleCalibMode]));
		w14.X = 12;
		w14.Y = 106;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.RollCalibMode = new global::Gtk.Button ();
		this.RollCalibMode.CanFocus = true;
		this.RollCalibMode.Name = "RollCalibMode";
		this.RollCalibMode.UseUnderline = true;
		this.RollCalibMode.Label = global::Mono.Unix.Catalog.GetString ("Cal. Roll");
		this.fixed1.Add (this.RollCalibMode);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.RollCalibMode]));
		w15.X = 111;
		w15.Y = 106;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.PitchCalibMode = new global::Gtk.Button ();
		this.PitchCalibMode.CanFocus = true;
		this.PitchCalibMode.Name = "PitchCalibMode";
		this.PitchCalibMode.UseUnderline = true;
		this.PitchCalibMode.Label = global::Mono.Unix.Catalog.GetString ("Cal. Pitch");
		this.fixed1.Add (this.PitchCalibMode);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.PitchCalibMode]));
		w16.X = 13;
		w16.Y = 141;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.YawCalibMode = new global::Gtk.Button ();
		this.YawCalibMode.CanFocus = true;
		this.YawCalibMode.Name = "YawCalibMode";
		this.YawCalibMode.UseUnderline = true;
		this.YawCalibMode.Label = global::Mono.Unix.Catalog.GetString ("Cal. Yaw");
		this.fixed1.Add (this.YawCalibMode);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.YawCalibMode]));
		w17.X = 95;
		w17.Y = 142;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ModesLabel = new global::Gtk.Label ();
		this.ModesLabel.Name = "ModesLabel";
		this.ModesLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Cur. Mode");
		this.fixed1.Add (this.ModesLabel);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ModesLabel]));
		w18.X = 16;
		w18.Y = 179;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CurMode = new global::Gtk.Label ();
		this.CurMode.Name = "CurMode";
		this.CurMode.LabelProp = global::Mono.Unix.Catalog.GetString ("Mode");
		this.fixed1.Add (this.CurMode);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CurMode]));
		w19.X = 93;
		w19.Y = 178;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.RollKi = new global::Gtk.Button ();
		this.RollKi.CanFocus = true;
		this.RollKi.Name = "RollKi";
		this.RollKi.UseUnderline = true;
		this.RollKi.Label = global::Mono.Unix.Catalog.GetString ("Roll Ki");
		this.fixed1.Add (this.RollKi);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.RollKi]));
		w20.X = 384;
		w20.Y = 9;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.RollCurrKi = new global::Gtk.Label ();
		this.RollCurrKi.Name = "RollCurrKi";
		this.RollCurrKi.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.RollCurrKi);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.RollCurrKi]));
		w21.X = 454;
		w21.Y = 14;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.PitchKp = new global::Gtk.Button ();
		this.PitchKp.CanFocus = true;
		this.PitchKp.Name = "PitchKp";
		this.PitchKp.UseUnderline = true;
		this.PitchKp.Label = global::Mono.Unix.Catalog.GetString ("Pitch Kp");
		this.fixed1.Add (this.PitchKp);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.PitchKp]));
		w22.X = 272;
		w22.Y = 42;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.PitchCurrKp = new global::Gtk.Label ();
		this.PitchCurrKp.Name = "PitchCurrKp";
		this.PitchCurrKp.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.PitchCurrKp);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.PitchCurrKp]));
		w23.X = 349;
		w23.Y = 45;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.TasLabel = new global::Gtk.Label ();
		this.TasLabel.Name = "TasLabel";
		this.TasLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Cur. TAS");
		this.fixed1.Add (this.TasLabel);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.TasLabel]));
		w24.X = 268;
		w24.Y = 184;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.TasEntry = new global::Gtk.Label ();
		this.TasEntry.Name = "TasEntry";
		this.TasEntry.LabelProp = global::Mono.Unix.Catalog.GetString ("000.00");
		this.fixed1.Add (this.TasEntry);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.TasEntry]));
		w25.X = 332;
		w25.Y = 182;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.NewTas = new global::Gtk.Button ();
		this.NewTas.CanFocus = true;
		this.NewTas.Name = "NewTas";
		this.NewTas.UseUnderline = true;
		this.NewTas.Label = global::Mono.Unix.Catalog.GetString ("New TAS");
		this.fixed1.Add (this.NewTas);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.NewTas]));
		w26.X = 260;
		w26.Y = 148;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.SelTas = new global::Gtk.Label ();
		this.SelTas.Name = "SelTas";
		this.SelTas.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.SelTas);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.SelTas]));
		w27.X = 338;
		w27.Y = 155;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.AltLabel = new global::Gtk.Label ();
		this.AltLabel.Name = "AltLabel";
		this.AltLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Cur. ALT");
		this.fixed1.Add (this.AltLabel);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.AltLabel]));
		w28.X = 386;
		w28.Y = 184;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.NewAlt = new global::Gtk.Button ();
		this.NewAlt.CanFocus = true;
		this.NewAlt.Name = "NewAlt";
		this.NewAlt.UseUnderline = true;
		this.NewAlt.Label = global::Mono.Unix.Catalog.GetString ("New ALT");
		this.fixed1.Add (this.NewAlt);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.NewAlt]));
		w29.X = 377;
		w29.Y = 149;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.SelAlt = new global::Gtk.Label ();
		this.SelAlt.Name = "SelAlt";
		this.SelAlt.LabelProp = global::Mono.Unix.Catalog.GetString ("0000");
		this.fixed1.Add (this.SelAlt);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.SelAlt]));
		w30.X = 449;
		w30.Y = 156;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.RollEntry = new global::Gtk.Label ();
		this.RollEntry.Name = "RollEntry";
		this.RollEntry.LabelProp = global::Mono.Unix.Catalog.GetString ("000.00");
		this.fixed1.Add (this.RollEntry);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.RollEntry]));
		w31.X = 555;
		w31.Y = 15;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.YawKp = new global::Gtk.Button ();
		this.YawKp.CanFocus = true;
		this.YawKp.Name = "YawKp";
		this.YawKp.UseUnderline = true;
		this.YawKp.Label = global::Mono.Unix.Catalog.GetString ("Yaw Kp");
		this.fixed1.Add (this.YawKp);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.YawKp]));
		w32.X = 273;
		w32.Y = 77;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.YawCurrKp = new global::Gtk.Label ();
		this.YawCurrKp.Name = "YawCurrKp";
		this.YawCurrKp.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.YawCurrKp);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.YawCurrKp]));
		w33.X = 344;
		w33.Y = 83;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.YawKi = new global::Gtk.Button ();
		this.YawKi.CanFocus = true;
		this.YawKi.Name = "YawKi";
		this.YawKi.UseUnderline = true;
		this.YawKi.Label = global::Mono.Unix.Catalog.GetString ("Yaw Ki");
		this.fixed1.Add (this.YawKi);
		global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.YawKi]));
		w34.X = 381;
		w34.Y = 74;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.YawCurrKi = new global::Gtk.Label ();
		this.YawCurrKi.Name = "YawCurrKi";
		this.YawCurrKi.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.YawCurrKi);
		global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.YawCurrKi]));
		w35.X = 445;
		w35.Y = 79;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.PitchEntry = new global::Gtk.Label ();
		this.PitchEntry.Name = "PitchEntry";
		this.PitchEntry.LabelProp = global::Mono.Unix.Catalog.GetString ("000.00");
		this.fixed1.Add (this.PitchEntry);
		global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.PitchEntry]));
		w36.X = 556;
		w36.Y = 44;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.YawEntry = new global::Gtk.Label ();
		this.YawEntry.Name = "YawEntry";
		this.YawEntry.LabelProp = global::Mono.Unix.Catalog.GetString ("000.00");
		this.fixed1.Add (this.YawEntry);
		global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.YawEntry]));
		w37.X = 555;
		w37.Y = 75;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.HeadLabel = new global::Gtk.Label ();
		this.HeadLabel.Name = "HeadLabel";
		this.HeadLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Cur. HEA");
		this.fixed1.Add (this.HeadLabel);
		global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.HeadLabel]));
		w38.X = 487;
		w38.Y = 181;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.YawLabel = new global::Gtk.Label ();
		this.YawLabel.Name = "YawLabel";
		this.YawLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Cur. Yaw");
		this.fixed1.Add (this.YawLabel);
		global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.YawLabel]));
		w39.X = 485;
		w39.Y = 77;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.RollLabel = new global::Gtk.Label ();
		this.RollLabel.Name = "RollLabel";
		this.RollLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Cur. Roll");
		this.fixed1.Add (this.RollLabel);
		global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.RollLabel]));
		w40.X = 491;
		w40.Y = 15;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ThrottleKp = new global::Gtk.Button ();
		this.ThrottleKp.CanFocus = true;
		this.ThrottleKp.Name = "ThrottleKp";
		this.ThrottleKp.UseUnderline = true;
		this.ThrottleKp.Label = global::Mono.Unix.Catalog.GetString ("Throt. Kp");
		this.fixed1.Add (this.ThrottleKp);
		global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ThrottleKp]));
		w41.X = 259;
		w41.Y = 111;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ThrottleCurrKp = new global::Gtk.Label ();
		this.ThrottleCurrKp.Name = "ThrottleCurrKp";
		this.ThrottleCurrKp.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.ThrottleCurrKp);
		global::Gtk.Fixed.FixedChild w42 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ThrottleCurrKp]));
		w42.X = 340;
		w42.Y = 116;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ThrottleKi = new global::Gtk.Button ();
		this.ThrottleKi.CanFocus = true;
		this.ThrottleKi.Name = "ThrottleKi";
		this.ThrottleKi.UseUnderline = true;
		this.ThrottleKi.Label = global::Mono.Unix.Catalog.GetString ("Throt. Ki");
		this.fixed1.Add (this.ThrottleKi);
		global::Gtk.Fixed.FixedChild w43 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ThrottleKi]));
		w43.X = 372;
		w43.Y = 112;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ThrottleCurrKi = new global::Gtk.Label ();
		this.ThrottleCurrKi.Name = "ThrottleCurrKi";
		this.ThrottleCurrKi.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.ThrottleCurrKi);
		global::Gtk.Fixed.FixedChild w44 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ThrottleCurrKi]));
		w44.X = 447;
		w44.Y = 116;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.PitchLabel = new global::Gtk.Label ();
		this.PitchLabel.Name = "PitchLabel";
		this.PitchLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Cur. Pitch");
		this.fixed1.Add (this.PitchLabel);
		global::Gtk.Fixed.FixedChild w45 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.PitchLabel]));
		w45.X = 487;
		w45.Y = 44;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ThorttleLabel = new global::Gtk.Label ();
		this.ThorttleLabel.Name = "ThorttleLabel";
		this.ThorttleLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Cur. Thot");
		this.fixed1.Add (this.ThorttleLabel);
		global::Gtk.Fixed.FixedChild w46 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ThorttleLabel]));
		w46.X = 483;
		w46.Y = 115;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ThrottleEntry = new global::Gtk.Label ();
		this.ThrottleEntry.Name = "ThrottleEntry";
		this.ThrottleEntry.LabelProp = global::Mono.Unix.Catalog.GetString ("000.00");
		this.fixed1.Add (this.ThrottleEntry);
		global::Gtk.Fixed.FixedChild w47 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ThrottleEntry]));
		w47.X = 555;
		w47.Y = 114;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CurAlt = new global::Gtk.Label ();
		this.CurAlt.Name = "CurAlt";
		this.CurAlt.LabelProp = global::Mono.Unix.Catalog.GetString ("0000");
		this.fixed1.Add (this.CurAlt);
		global::Gtk.Fixed.FixedChild w48 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CurAlt]));
		w48.X = 449;
		w48.Y = 182;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.NewHeading = new global::Gtk.Button ();
		this.NewHeading.CanFocus = true;
		this.NewHeading.Name = "NewHeading";
		this.NewHeading.UseUnderline = true;
		this.NewHeading.Label = global::Mono.Unix.Catalog.GetString ("New HEA");
		this.fixed1.Add (this.NewHeading);
		global::Gtk.Fixed.FixedChild w49 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.NewHeading]));
		w49.X = 484;
		w49.Y = 146;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.SelHEad = new global::Gtk.Label ();
		this.SelHEad.Name = "SelHEad";
		this.SelHEad.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.SelHEad);
		global::Gtk.Fixed.FixedChild w50 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.SelHEad]));
		w50.X = 567;
		w50.Y = 151;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CurHead = new global::Gtk.Label ();
		this.CurHead.Name = "CurHead";
		this.CurHead.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.CurHead);
		global::Gtk.Fixed.FixedChild w51 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CurHead]));
		w51.X = 565;
		w51.Y = 177;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.NewRollRef = new global::Gtk.Button ();
		this.NewRollRef.CanFocus = true;
		this.NewRollRef.Name = "NewRollRef";
		this.NewRollRef.UseUnderline = true;
		this.NewRollRef.Label = global::Mono.Unix.Catalog.GetString ("New Roll Ref");
		this.fixed1.Add (this.NewRollRef);
		global::Gtk.Fixed.FixedChild w52 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.NewRollRef]));
		w52.X = 259;
		w52.Y = 208;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.NewPitchRef = new global::Gtk.Button ();
		this.NewPitchRef.CanFocus = true;
		this.NewPitchRef.Name = "NewPitchRef";
		this.NewPitchRef.UseUnderline = true;
		this.NewPitchRef.Label = global::Mono.Unix.Catalog.GetString ("New Pitch Ref");
		this.fixed1.Add (this.NewPitchRef);
		global::Gtk.Fixed.FixedChild w53 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.NewPitchRef]));
		w53.X = 259;
		w53.Y = 241;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.NewYawRef = new global::Gtk.Button ();
		this.NewYawRef.CanFocus = true;
		this.NewYawRef.Name = "NewYawRef";
		this.NewYawRef.UseUnderline = true;
		this.NewYawRef.Label = global::Mono.Unix.Catalog.GetString ("New Yaw Ref");
		this.fixed1.Add (this.NewYawRef);
		global::Gtk.Fixed.FixedChild w54 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.NewYawRef]));
		w54.X = 414;
		w54.Y = 208;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.NewThrottleRef = new global::Gtk.Button ();
		this.NewThrottleRef.CanFocus = true;
		this.NewThrottleRef.Name = "NewThrottleRef";
		this.NewThrottleRef.UseUnderline = true;
		this.NewThrottleRef.Label = global::Mono.Unix.Catalog.GetString ("New Throt Ref");
		this.fixed1.Add (this.NewThrottleRef);
		global::Gtk.Fixed.FixedChild w55 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.NewThrottleRef]));
		w55.X = 414;
		w55.Y = 240;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CurRollRef = new global::Gtk.Label ();
		this.CurRollRef.Name = "CurRollRef";
		this.CurRollRef.LabelProp = global::Mono.Unix.Catalog.GetString ("00.00");
		this.fixed1.Add (this.CurRollRef);
		global::Gtk.Fixed.FixedChild w56 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CurRollRef]));
		w56.X = 368;
		w56.Y = 212;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CurPitchRef = new global::Gtk.Label ();
		this.CurPitchRef.Name = "CurPitchRef";
		this.CurPitchRef.LabelProp = global::Mono.Unix.Catalog.GetString ("00.00");
		this.fixed1.Add (this.CurPitchRef);
		global::Gtk.Fixed.FixedChild w57 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CurPitchRef]));
		w57.X = 369;
		w57.Y = 244;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CurYawRef = new global::Gtk.Label ();
		this.CurYawRef.Name = "CurYawRef";
		this.CurYawRef.LabelProp = global::Mono.Unix.Catalog.GetString ("000.00");
		this.fixed1.Add (this.CurYawRef);
		global::Gtk.Fixed.FixedChild w58 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CurYawRef]));
		w58.X = 532;
		w58.Y = 213;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CurThrotRef = new global::Gtk.Label ();
		this.CurThrotRef.Name = "CurThrotRef";
		this.CurThrotRef.LabelProp = global::Mono.Unix.Catalog.GetString ("000.00");
		this.fixed1.Add (this.CurThrotRef);
		global::Gtk.Fixed.FixedChild w59 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CurThrotRef]));
		w59.X = 533;
		w59.Y = 243;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.InCh2 = new global::Gtk.Label ();
		this.InCh2.Name = "InCh2";
		this.InCh2.LabelProp = global::Mono.Unix.Catalog.GetString ("IN Ch 2");
		this.fixed1.Add (this.InCh2);
		global::Gtk.Fixed.FixedChild w60 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.InCh2]));
		w60.X = 261;
		w60.Y = 295;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.InCh1 = new global::Gtk.Label ();
		this.InCh1.Name = "InCh1";
		this.InCh1.LabelProp = global::Mono.Unix.Catalog.GetString ("IN Ch 1 ");
		this.fixed1.Add (this.InCh1);
		global::Gtk.Fixed.FixedChild w61 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.InCh1]));
		w61.X = 261;
		w61.Y = 277;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.InCh3 = new global::Gtk.Label ();
		this.InCh3.Name = "InCh3";
		this.InCh3.LabelProp = global::Mono.Unix.Catalog.GetString ("IN Ch 3");
		this.fixed1.Add (this.InCh3);
		global::Gtk.Fixed.FixedChild w62 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.InCh3]));
		w62.X = 260;
		w62.Y = 312;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.InCh1Val = new global::Gtk.Label ();
		this.InCh1Val.Name = "InCh1Val";
		this.InCh1Val.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.InCh1Val);
		global::Gtk.Fixed.FixedChild w63 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.InCh1Val]));
		w63.X = 313;
		w63.Y = 277;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.InCh2Val = new global::Gtk.Label ();
		this.InCh2Val.Name = "InCh2Val";
		this.InCh2Val.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.InCh2Val);
		global::Gtk.Fixed.FixedChild w64 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.InCh2Val]));
		w64.X = 313;
		w64.Y = 292;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.InCh4Val = new global::Gtk.Label ();
		this.InCh4Val.Name = "InCh4Val";
		this.InCh4Val.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.InCh4Val);
		global::Gtk.Fixed.FixedChild w65 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.InCh4Val]));
		w65.X = 313;
		w65.Y = 327;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.InCh3Val = new global::Gtk.Label ();
		this.InCh3Val.Name = "InCh3Val";
		this.InCh3Val.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.InCh3Val);
		global::Gtk.Fixed.FixedChild w66 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.InCh3Val]));
		w66.X = 313;
		w66.Y = 310;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.InCh4 = new global::Gtk.Label ();
		this.InCh4.Name = "InCh4";
		this.InCh4.LabelProp = global::Mono.Unix.Catalog.GetString ("IN Ch 4");
		this.fixed1.Add (this.InCh4);
		global::Gtk.Fixed.FixedChild w67 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.InCh4]));
		w67.X = 259;
		w67.Y = 327;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ThrottleMeanVal = new global::Gtk.Button ();
		this.ThrottleMeanVal.CanFocus = true;
		this.ThrottleMeanVal.Name = "ThrottleMeanVal";
		this.ThrottleMeanVal.UseUnderline = true;
		this.ThrottleMeanVal.Label = global::Mono.Unix.Catalog.GetString ("Throt. Mean Val.");
		this.fixed1.Add (this.ThrottleMeanVal);
		global::Gtk.Fixed.FixedChild w68 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ThrottleMeanVal]));
		w68.X = 7;
		w68.Y = 209;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CurThrottleMeanVal = new global::Gtk.Label ();
		this.CurThrottleMeanVal.Name = "CurThrottleMeanVal";
		this.CurThrottleMeanVal.LabelProp = global::Mono.Unix.Catalog.GetString ("0000");
		this.fixed1.Add (this.CurThrottleMeanVal);
		global::Gtk.Fixed.FixedChild w69 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CurThrottleMeanVal]));
		w69.X = 134;
		w69.Y = 213;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.RollMeanVal = new global::Gtk.Button ();
		this.RollMeanVal.CanFocus = true;
		this.RollMeanVal.Name = "RollMeanVal";
		this.RollMeanVal.UseUnderline = true;
		this.RollMeanVal.Label = global::Mono.Unix.Catalog.GetString ("Roll Mean Val.");
		this.fixed1.Add (this.RollMeanVal);
		global::Gtk.Fixed.FixedChild w70 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.RollMeanVal]));
		w70.X = 8;
		w70.Y = 242;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.PitchMeanVal = new global::Gtk.Button ();
		this.PitchMeanVal.CanFocus = true;
		this.PitchMeanVal.Name = "PitchMeanVal";
		this.PitchMeanVal.UseUnderline = true;
		this.PitchMeanVal.Label = global::Mono.Unix.Catalog.GetString ("Pitch Mean Val.");
		this.fixed1.Add (this.PitchMeanVal);
		global::Gtk.Fixed.FixedChild w71 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.PitchMeanVal]));
		w71.X = 9;
		w71.Y = 274;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CurRollMeanVal = new global::Gtk.Label ();
		this.CurRollMeanVal.Name = "CurRollMeanVal";
		this.CurRollMeanVal.LabelProp = global::Mono.Unix.Catalog.GetString ("0000");
		this.fixed1.Add (this.CurRollMeanVal);
		global::Gtk.Fixed.FixedChild w72 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CurRollMeanVal]));
		w72.X = 135;
		w72.Y = 245;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.YawMeanVal = new global::Gtk.Button ();
		this.YawMeanVal.CanFocus = true;
		this.YawMeanVal.Name = "YawMeanVal";
		this.YawMeanVal.UseUnderline = true;
		this.YawMeanVal.Label = global::Mono.Unix.Catalog.GetString ("Yaw Mean Val.");
		this.fixed1.Add (this.YawMeanVal);
		global::Gtk.Fixed.FixedChild w73 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.YawMeanVal]));
		w73.X = 9;
		w73.Y = 306;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CurPitchMeanVal = new global::Gtk.Label ();
		this.CurPitchMeanVal.Name = "CurPitchMeanVal";
		this.CurPitchMeanVal.LabelProp = global::Mono.Unix.Catalog.GetString ("0000");
		this.fixed1.Add (this.CurPitchMeanVal);
		global::Gtk.Fixed.FixedChild w74 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CurPitchMeanVal]));
		w74.X = 135;
		w74.Y = 277;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CurYawMeanVal = new global::Gtk.Label ();
		this.CurYawMeanVal.Name = "CurYawMeanVal";
		this.CurYawMeanVal.LabelProp = global::Mono.Unix.Catalog.GetString ("0000");
		this.fixed1.Add (this.CurYawMeanVal);
		global::Gtk.Fixed.FixedChild w75 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CurYawMeanVal]));
		w75.X = 135;
		w75.Y = 308;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ThrottleInitialValue = new global::Gtk.Button ();
		this.ThrottleInitialValue.CanFocus = true;
		this.ThrottleInitialValue.Name = "ThrottleInitialValue";
		this.ThrottleInitialValue.UseUnderline = true;
		this.ThrottleInitialValue.Label = global::Mono.Unix.Catalog.GetString ("Throt. Init. Val.");
		this.fixed1.Add (this.ThrottleInitialValue);
		global::Gtk.Fixed.FixedChild w76 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ThrottleInitialValue]));
		w76.X = 11;
		w76.Y = 343;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.RollInitialValue = new global::Gtk.Button ();
		this.RollInitialValue.CanFocus = true;
		this.RollInitialValue.Name = "RollInitialValue";
		this.RollInitialValue.UseUnderline = true;
		this.RollInitialValue.Label = global::Mono.Unix.Catalog.GetString ("Roll Init. Val.");
		this.fixed1.Add (this.RollInitialValue);
		global::Gtk.Fixed.FixedChild w77 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.RollInitialValue]));
		w77.X = 11;
		w77.Y = 381;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.YawInitialValue = new global::Gtk.Button ();
		this.YawInitialValue.CanFocus = true;
		this.YawInitialValue.Name = "YawInitialValue";
		this.YawInitialValue.UseUnderline = true;
		this.YawInitialValue.Label = global::Mono.Unix.Catalog.GetString ("Yaw Init. Val.");
		this.fixed1.Add (this.YawInitialValue);
		global::Gtk.Fixed.FixedChild w78 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.YawInitialValue]));
		w78.X = 12;
		w78.Y = 455;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.PitchInitialValue = new global::Gtk.Button ();
		this.PitchInitialValue.CanFocus = true;
		this.PitchInitialValue.Name = "PitchInitialValue";
		this.PitchInitialValue.UseUnderline = true;
		this.PitchInitialValue.Label = global::Mono.Unix.Catalog.GetString ("Pitch Init. Val.");
		this.fixed1.Add (this.PitchInitialValue);
		global::Gtk.Fixed.FixedChild w79 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.PitchInitialValue]));
		w79.X = 11;
		w79.Y = 416;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CurThrotInitialValue = new global::Gtk.Label ();
		this.CurThrotInitialValue.Name = "CurThrotInitialValue";
		this.CurThrotInitialValue.LabelProp = global::Mono.Unix.Catalog.GetString ("00.00");
		this.fixed1.Add (this.CurThrotInitialValue);
		global::Gtk.Fixed.FixedChild w80 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CurThrotInitialValue]));
		w80.X = 129;
		w80.Y = 347;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CurRollInitialVal = new global::Gtk.Label ();
		this.CurRollInitialVal.Name = "CurRollInitialVal";
		this.CurRollInitialVal.LabelProp = global::Mono.Unix.Catalog.GetString ("00.00");
		this.fixed1.Add (this.CurRollInitialVal);
		global::Gtk.Fixed.FixedChild w81 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CurRollInitialVal]));
		w81.X = 129;
		w81.Y = 384;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CurPitchInitialVal = new global::Gtk.Label ();
		this.CurPitchInitialVal.Name = "CurPitchInitialVal";
		this.CurPitchInitialVal.LabelProp = global::Mono.Unix.Catalog.GetString ("00.00");
		this.fixed1.Add (this.CurPitchInitialVal);
		global::Gtk.Fixed.FixedChild w82 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CurPitchInitialVal]));
		w82.X = 129;
		w82.Y = 418;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ActThrottle = new global::Gtk.Button ();
		this.ActThrottle.CanFocus = true;
		this.ActThrottle.Name = "ActThrottle";
		this.ActThrottle.UseUnderline = true;
		this.ActThrottle.Label = global::Mono.Unix.Catalog.GetString ("ACT/DACT THROTTLE");
		this.fixed1.Add (this.ActThrottle);
		global::Gtk.Fixed.FixedChild w83 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ActThrottle]));
		w83.X = 256;
		w83.Y = 353;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ActRoll = new global::Gtk.Button ();
		this.ActRoll.CanFocus = true;
		this.ActRoll.Name = "ActRoll";
		this.ActRoll.UseUnderline = true;
		this.ActRoll.Label = global::Mono.Unix.Catalog.GetString ("ACT/DACT ROLL");
		this.fixed1.Add (this.ActRoll);
		global::Gtk.Fixed.FixedChild w84 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ActRoll]));
		w84.X = 256;
		w84.Y = 386;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ActPitch = new global::Gtk.Button ();
		this.ActPitch.CanFocus = true;
		this.ActPitch.Name = "ActPitch";
		this.ActPitch.UseUnderline = true;
		this.ActPitch.Label = global::Mono.Unix.Catalog.GetString ("ACT/DACT PITCH");
		this.fixed1.Add (this.ActPitch);
		global::Gtk.Fixed.FixedChild w85 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ActPitch]));
		w85.X = 254;
		w85.Y = 419;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ActYaw = new global::Gtk.Button ();
		this.ActYaw.CanFocus = true;
		this.ActYaw.Name = "ActYaw";
		this.ActYaw.UseUnderline = true;
		this.ActYaw.Label = global::Mono.Unix.Catalog.GetString ("ACT/DACT YAW");
		this.fixed1.Add (this.ActYaw);
		global::Gtk.Fixed.FixedChild w86 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ActYaw]));
		w86.X = 253;
		w86.Y = 452;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CurActThrottle = new global::Gtk.Label ();
		this.CurActThrottle.Name = "CurActThrottle";
		this.CurActThrottle.LabelProp = global::Mono.Unix.Catalog.GetString ("TRUE");
		this.fixed1.Add (this.CurActThrottle);
		global::Gtk.Fixed.FixedChild w87 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CurActThrottle]));
		w87.X = 426;
		w87.Y = 355;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CuActRoll = new global::Gtk.Label ();
		this.CuActRoll.Name = "CuActRoll";
		this.CuActRoll.LabelProp = global::Mono.Unix.Catalog.GetString ("TRUE");
		this.fixed1.Add (this.CuActRoll);
		global::Gtk.Fixed.FixedChild w88 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CuActRoll]));
		w88.X = 424;
		w88.Y = 387;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CurActPitch = new global::Gtk.Label ();
		this.CurActPitch.Name = "CurActPitch";
		this.CurActPitch.LabelProp = global::Mono.Unix.Catalog.GetString ("TRUE");
		this.fixed1.Add (this.CurActPitch);
		global::Gtk.Fixed.FixedChild w89 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CurActPitch]));
		w89.X = 422;
		w89.Y = 418;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CurActYaw = new global::Gtk.Label ();
		this.CurActYaw.Name = "CurActYaw";
		this.CurActYaw.LabelProp = global::Mono.Unix.Catalog.GetString ("TRUE");
		this.fixed1.Add (this.CurActYaw);
		global::Gtk.Fixed.FixedChild w90 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CurActYaw]));
		w90.X = 422;
		w90.Y = 454;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GetInitialData = new global::Gtk.Button ();
		this.GetInitialData.CanFocus = true;
		this.GetInitialData.Name = "GetInitialData";
		this.GetInitialData.UseUnderline = true;
		this.GetInitialData.Label = global::Mono.Unix.Catalog.GetString ("Get Initial Data");
		this.fixed1.Add (this.GetInitialData);
		global::Gtk.Fixed.FixedChild w91 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GetInitialData]));
		w91.X = 9;
		w91.Y = 498;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.OutCh1Val = new global::Gtk.Label ();
		this.OutCh1Val.Name = "OutCh1Val";
		this.OutCh1Val.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.OutCh1Val);
		global::Gtk.Fixed.FixedChild w92 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.OutCh1Val]));
		w92.X = 476;
		w92.Y = 275;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.OutCh2Val = new global::Gtk.Label ();
		this.OutCh2Val.Name = "OutCh2Val";
		this.OutCh2Val.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.OutCh2Val);
		global::Gtk.Fixed.FixedChild w93 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.OutCh2Val]));
		w93.X = 476;
		w93.Y = 291;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.OutCh3Val = new global::Gtk.Label ();
		this.OutCh3Val.Name = "OutCh3Val";
		this.OutCh3Val.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.OutCh3Val);
		global::Gtk.Fixed.FixedChild w94 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.OutCh3Val]));
		w94.X = 476;
		w94.Y = 308;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.OutCh4Val = new global::Gtk.Label ();
		this.OutCh4Val.Name = "OutCh4Val";
		this.OutCh4Val.LabelProp = global::Mono.Unix.Catalog.GetString ("000");
		this.fixed1.Add (this.OutCh4Val);
		global::Gtk.Fixed.FixedChild w95 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.OutCh4Val]));
		w95.X = 475;
		w95.Y = 326;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.OutCh1 = new global::Gtk.Label ();
		this.OutCh1.Name = "OutCh1";
		this.OutCh1.LabelProp = global::Mono.Unix.Catalog.GetString ("OUT Ch 1");
		this.fixed1.Add (this.OutCh1);
		global::Gtk.Fixed.FixedChild w96 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.OutCh1]));
		w96.X = 400;
		w96.Y = 275;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.OutCh2 = new global::Gtk.Label ();
		this.OutCh2.Name = "OutCh2";
		this.OutCh2.LabelProp = global::Mono.Unix.Catalog.GetString ("OUT Ch 2");
		this.fixed1.Add (this.OutCh2);
		global::Gtk.Fixed.FixedChild w97 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.OutCh2]));
		w97.X = 399;
		w97.Y = 293;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.OutCh3 = new global::Gtk.Label ();
		this.OutCh3.Name = "OutCh3";
		this.OutCh3.LabelProp = global::Mono.Unix.Catalog.GetString ("OUT Ch 3");
		this.fixed1.Add (this.OutCh3);
		global::Gtk.Fixed.FixedChild w98 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.OutCh3]));
		w98.X = 403;
		w98.Y = 308;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.OutCh4 = new global::Gtk.Label ();
		this.OutCh4.Name = "OutCh4";
		this.OutCh4.LabelProp = global::Mono.Unix.Catalog.GetString ("OUT Ch 4");
		this.fixed1.Add (this.OutCh4);
		global::Gtk.Fixed.FixedChild w99 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.OutCh4]));
		w99.X = 400;
		w99.Y = 323;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.InCh1Width = new global::Gtk.Label ();
		this.InCh1Width.Name = "InCh1Width";
		this.InCh1Width.LabelProp = global::Mono.Unix.Catalog.GetString ("0000");
		this.fixed1.Add (this.InCh1Width);
		global::Gtk.Fixed.FixedChild w100 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.InCh1Width]));
		w100.X = 346;
		w100.Y = 278;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.InCh2Width = new global::Gtk.Label ();
		this.InCh2Width.Name = "InCh2Width";
		this.InCh2Width.LabelProp = global::Mono.Unix.Catalog.GetString ("0000");
		this.fixed1.Add (this.InCh2Width);
		global::Gtk.Fixed.FixedChild w101 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.InCh2Width]));
		w101.X = 346;
		w101.Y = 292;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.InCh3Width = new global::Gtk.Label ();
		this.InCh3Width.Name = "InCh3Width";
		this.InCh3Width.LabelProp = global::Mono.Unix.Catalog.GetString ("0000");
		this.fixed1.Add (this.InCh3Width);
		global::Gtk.Fixed.FixedChild w102 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.InCh3Width]));
		w102.X = 349;
		w102.Y = 308;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.InCh4Width = new global::Gtk.Label ();
		this.InCh4Width.Name = "InCh4Width";
		this.InCh4Width.LabelProp = global::Mono.Unix.Catalog.GetString ("0000");
		this.fixed1.Add (this.InCh4Width);
		global::Gtk.Fixed.FixedChild w103 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.InCh4Width]));
		w103.X = 347;
		w103.Y = 326;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.OutCh3Width = new global::Gtk.Label ();
		this.OutCh3Width.Name = "OutCh3Width";
		this.OutCh3Width.LabelProp = global::Mono.Unix.Catalog.GetString ("0000");
		this.fixed1.Add (this.OutCh3Width);
		global::Gtk.Fixed.FixedChild w104 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.OutCh3Width]));
		w104.X = 505;
		w104.Y = 304;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.OutCh4Width = new global::Gtk.Label ();
		this.OutCh4Width.Name = "OutCh4Width";
		this.OutCh4Width.LabelProp = global::Mono.Unix.Catalog.GetString ("0000");
		this.fixed1.Add (this.OutCh4Width);
		global::Gtk.Fixed.FixedChild w105 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.OutCh4Width]));
		w105.X = 506;
		w105.Y = 323;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.OutCh2Width = new global::Gtk.Label ();
		this.OutCh2Width.Name = "OutCh2Width";
		this.OutCh2Width.LabelProp = global::Mono.Unix.Catalog.GetString ("0000");
		this.fixed1.Add (this.OutCh2Width);
		global::Gtk.Fixed.FixedChild w106 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.OutCh2Width]));
		w106.X = 507;
		w106.Y = 287;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.OutCh1Width = new global::Gtk.Label ();
		this.OutCh1Width.Name = "OutCh1Width";
		this.OutCh1Width.LabelProp = global::Mono.Unix.Catalog.GetString ("0000");
		this.fixed1.Add (this.OutCh1Width);
		global::Gtk.Fixed.FixedChild w107 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.OutCh1Width]));
		w107.X = 506;
		w107.Y = 271;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GetCurrYaw = new global::Gtk.Button ();
		this.GetCurrYaw.CanFocus = true;
		this.GetCurrYaw.Name = "GetCurrYaw";
		this.GetCurrYaw.UseUnderline = true;
		this.GetCurrYaw.Label = global::Mono.Unix.Catalog.GetString ("Get Current");
		this.fixed1.Add (this.GetCurrYaw);
		global::Gtk.Fixed.FixedChild w108 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GetCurrYaw]));
		w108.X = 112;
		w108.Y = 453;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CurYawInitVal = new global::Gtk.Label ();
		this.CurYawInitVal.Name = "CurYawInitVal";
		this.CurYawInitVal.LabelProp = global::Mono.Unix.Catalog.GetString ("000.00");
		this.fixed1.Add (this.CurYawInitVal);
		global::Gtk.Fixed.FixedChild w109 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CurYawInitVal]));
		w109.X = 201;
		w109.Y = 458;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 670;
		this.DefaultHeight = 704;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler (this.AcceptQueryEvent);
		this.RollKp.Clicked += new global::System.EventHandler (this.OnRollKpClicked);
		this.PitchKi.Clicked += new global::System.EventHandler (this.OnPitchKiClicked);
		this.ManualMode.Clicked += new global::System.EventHandler (this.OnManualModeClicked);
		this.DirectedMode.Clicked += new global::System.EventHandler (this.OnDirectedModeClicked);
		this.AutoMode.Clicked += new global::System.EventHandler (this.OnAutoModeClicked);
		this.ThrottleCalibMode.Clicked += new global::System.EventHandler (this.OnThrottleCalibModeClicked);
		this.RollCalibMode.Clicked += new global::System.EventHandler (this.OnRollCalibModeClicked);
		this.PitchCalibMode.Clicked += new global::System.EventHandler (this.OnPitchCalibModeClicked);
		this.YawCalibMode.Clicked += new global::System.EventHandler (this.OnYawCalibModeClicked);
		this.RollKi.Clicked += new global::System.EventHandler (this.OnRollKiClicked);
		this.PitchKp.Clicked += new global::System.EventHandler (this.OnPitchKpClicked);
		this.NewTas.Clicked += new global::System.EventHandler (this.OnNewTasClicked);
		this.NewAlt.Clicked += new global::System.EventHandler (this.OnNewAltClicked);
		this.YawKp.Clicked += new global::System.EventHandler (this.OnYawKpClicked);
		this.YawKi.Clicked += new global::System.EventHandler (this.OnYawKiClicked);
		this.ThrottleKp.Clicked += new global::System.EventHandler (this.OnThrottleKpClicked);
		this.ThrottleKi.Clicked += new global::System.EventHandler (this.OnThrottleKiClicked);
		this.NewHeading.Clicked += new global::System.EventHandler (this.OnNewHeadingClicked);
		this.NewRollRef.Clicked += new global::System.EventHandler (this.OnNewRollRefClicked);
		this.NewPitchRef.Clicked += new global::System.EventHandler (this.OnNewPitchRefClicked);
		this.NewYawRef.Clicked += new global::System.EventHandler (this.OnNewYawRefClicked);
		this.NewThrottleRef.Clicked += new global::System.EventHandler (this.OnNewThrottleRefClicked);
		this.ThrottleMeanVal.Clicked += new global::System.EventHandler (this.OnThrottleMeanValClicked);
		this.RollMeanVal.Clicked += new global::System.EventHandler (this.OnRollMeanValClicked);
		this.PitchMeanVal.Clicked += new global::System.EventHandler (this.OnPitchMeanValClicked);
		this.YawMeanVal.Clicked += new global::System.EventHandler (this.OnYawMeanValClicked);
		this.ThrottleInitialValue.Clicked += new global::System.EventHandler (this.OnThrottleInitialValueClicked);
		this.RollInitialValue.Clicked += new global::System.EventHandler (this.OnRollInitialValueClicked);
		this.YawInitialValue.Clicked += new global::System.EventHandler (this.OnYawInitialValueClicked);
		this.PitchInitialValue.Clicked += new global::System.EventHandler (this.OnPitchInitialValueClicked);
		this.ActThrottle.Clicked += new global::System.EventHandler (this.OnThrottleClicked);
		this.ActRoll.Clicked += new global::System.EventHandler (this.OnRollClicked);
		this.ActPitch.Clicked += new global::System.EventHandler (this.OnActPitchClicked);
		this.ActYaw.Clicked += new global::System.EventHandler (this.OnActYawClicked);
		this.GetInitialData.Clicked += new global::System.EventHandler (this.OnGetInitialDataClicked);
		this.GetCurrYaw.Clicked += new global::System.EventHandler (this.OnGetCurrYawClicked);
	}
}
