language: c
 
os:
  - linux
  - osx
#whitelist
branches:
  only:
    - master
    
git:
  submodules: false

install:
  - sudo apt-get install mono-devel mono-gmcs
 
script:
  - source ./alternative.core-compile.sh
  - ls
  - source ./alternative-travis-init.sh
  - ls AlterNative.Core.bin
  - ls AlterNative.Core.bin/bin
  - ls AlterNative.Core.bin/bin/Debug
  - echo $ALTERNATIVE_BIN_PATH
  - alternative new test
  - cd test
  - "[[ -f CMakeLists.txt && -f Program.cpp && -f Program.h && -f main.cpp ]]"
 

notifications:
 email: true
