language: c
 
#whitelist
branches:
  only:
    - master
    
git:
  submodules: false

install:
  - sudo apt-get install mono-devel mono-gmcs
 
script:
  - source ./alternative.core-compile.sh

notifications:
 email: true
