@ECHO OFF

:: 
:: ALTERNATIVE_PATH
::
SET ALTERNATIVE_HOME=%CD%

::
:: ALTERNATIVE_BIN_PATH
::
SET ALTERNATIVE_BIN_PATH=%ALTERNATIVE_HOME%\AlterNative\bin\Debug

::
:: ALTERNATIVE_BIN
::
SET ALTERNATIVE_BIN=%ALTERNATIVE_HOME%\AlterNative\bin\Debug\AlterNative.exe

::
:: CPP_LIB_PATH
::
SET ALTERNATIVE_CPP_LIB_PATH=%ALTERNATIVE_HOME%\Lib

::
:: PATH 
::
SET PATH=%PATH%;%ALTERNATIVE_BIN_PATH%

     
       
