var namespace_system =
[
    [ "__Internal__", "namespace_system_1_1_____internal____.html", "namespace_system_1_1_____internal____" ],
    [ "Collections", "namespace_system_1_1_collections.html", "namespace_system_1_1_collections" ],
    [ "IO", "namespace_system_1_1_i_o.html", "namespace_system_1_1_i_o" ],
    [ "Text", "namespace_system_1_1_text.html", "namespace_system_1_1_text" ],
    [ "Threading", "namespace_system_1_1_threading.html", "namespace_system_1_1_threading" ],
    [ "ArgumentException", "class_system_1_1_argument_exception.html", "class_system_1_1_argument_exception" ],
    [ "ArgumentNullException", "class_system_1_1_argument_null_exception.html", "class_system_1_1_argument_null_exception" ],
    [ "ArgumentOutOfRangeException", "class_system_1_1_argument_out_of_range_exception.html", "class_system_1_1_argument_out_of_range_exception" ],
    [ "Array", "class_system_1_1_array.html", "class_system_1_1_array" ],
    [ "Box_T", "class_system_1_1_box___t.html", "class_system_1_1_box___t" ],
    [ "Console", "class_system_1_1_console.html", null ],
    [ "Convert", "class_system_1_1_convert.html", null ],
    [ "DateTime", "class_system_1_1_date_time.html", "class_system_1_1_date_time" ],
    [ "Delegate", "class_system_1_1_delegate.html", "class_system_1_1_delegate" ],
    [ "Double", "struct_system_1_1_double.html", null ],
    [ "Event", "class_system_1_1_event.html", null ],
    [ "Exception", "class_system_1_1_exception.html", "class_system_1_1_exception" ],
    [ "Float", "struct_system_1_1_float.html", null ],
    [ "GC", "class_system_1_1_g_c.html", null ],
    [ "IDisposable", "class_system_1_1_i_disposable.html", "class_system_1_1_i_disposable" ],
    [ "Int", "struct_system_1_1_int.html", null ],
    [ "Int32", "struct_system_1_1_int32.html", null ],
    [ "IntPtr", "struct_system_1_1_int_ptr.html", "struct_system_1_1_int_ptr" ],
    [ "InvalidOperationException", "class_system_1_1_invalid_operation_exception.html", "class_system_1_1_invalid_operation_exception" ],
    [ "Long", "struct_system_1_1_long.html", null ],
    [ "Math", "class_system_1_1_math.html", null ],
    [ "NotImplementedException", "class_system_1_1_not_implemented_exception.html", "class_system_1_1_not_implemented_exception" ],
    [ "Object", "class_system_1_1_object.html", "class_system_1_1_object" ],
    [ "ObjectDisposedException", "class_system_1_1_object_disposed_exception.html", "class_system_1_1_object_disposed_exception" ],
    [ "Random", "class_system_1_1_random.html", "class_system_1_1_random" ],
    [ "String", "class_system_1_1_string.html", "class_system_1_1_string" ],
    [ "SystemException", "class_system_1_1_system_exception.html", "class_system_1_1_system_exception" ],
    [ "TimeSpan", "class_system_1_1_time_span.html", "class_system_1_1_time_span" ],
    [ "ValueType", "struct_system_1_1_value_type.html", null ]
];